name: 'Superblocks Export'
description: 'Pull application-specific components source code from Superblocks'
inputs:
  sha:
    description: 'Commit to pull changes for'
    default: 'HEAD'
  token:
    description: 'The Superblocks access token to use'
    required: true
  domain:
    description: 'The Superblocks domain where applications are hosted'
    default: 'app.superblocks.com'
  path:
    description: 'The relative path to the Superblocks config file'
    default: '.superblocks/superblocks.json'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sha }}
    - ${{ inputs.token }}
    - ${{ inputs.domain }}
    - ${{ inputs.path }}
  env:
    SUPERBLOCKS_AUTHOR_NAME: 'superblocks-app[bot]'
    SUPERBLOCKS_AUTHOR_EMAIL: '142439023+superblocks-app[bot]@users.noreply.github.com'
